# Generated by Django 2.2.6 on 2019-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='dob',
            field=models.DateField(default='1997-01-01'),
        ),
    ]
