# Generated by Django 2.2.6 on 2019-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_userprofileinfo_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
