# Generated by Django 2.2.6 on 2019-10-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_userprofileinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
