# Generated by Django 2.2.6 on 2019-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_auto_20191010_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pics/kishan.jpg', upload_to='profile_pics/'),
        ),
    ]
