# Generated by Django 2.2.6 on 2019-10-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0012_auto_20191010_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='biography',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
