# Generated by Django 2.1.5 on 2019-10-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0013_userprofileinfo_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
