# Generated by Django 2.1.5 on 2019-10-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_auto_20191012_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='privacy_dob',
            field=models.CharField(default='Everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='privacy_email',
            field=models.CharField(default='Everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='privacy_phone',
            field=models.CharField(default='Everyone', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='privacy_posts',
            field=models.CharField(default='Everyone', max_length=10),
        ),
    ]
