# Generated by Django 2.0.5 on 2019-10-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0016_auto_20191029_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='balance',
            field=models.CharField(default=5000, max_length=15),
        ),
    ]
