# Generated by Django 2.0.5 on 2019-10-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0019_userprofileinfo_group_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
