# Generated by Django 2.1.5 on 2019-10-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mfa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='u2fkey',
            name='user',
        ),
        migrations.DeleteModel(
            name='U2FKey',
        ),
    ]
