# Generated by Django 2.1.5 on 2019-10-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageprofileinfo',
            name='page_pic',
            field=models.ImageField(blank=True, default='group_profile_pics/logo.png', upload_to='page_profile_pic/'),
        ),
    ]
