# Generated by Django 2.1.5 on 2019-10-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191027_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='page',
            field=models.ForeignKey(null=5, on_delete=django.db.models.deletion.CASCADE, to='pages.PageProfileInfo'),
            preserve_default=5,
        ),
    ]
