# Generated by Django 2.1.5 on 2019-10-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191027_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageprofileinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='pageprofileinfo',
            name='page',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
