# Generated by Django 2.1.5 on 2019-10-27 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191027_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepost',
            name='page',
        ),
    ]
