# Generated by Django 2.1.5 on 2019-10-27 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_pagepost_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagepost',
            name='page',
            field=models.ForeignKey(null='Null', on_delete=django.db.models.deletion.CASCADE, to='pages.PageProfileInfo'),
            preserve_default='Null',
        ),
    ]
