# Generated by Django 2.1.5 on 2019-10-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20191027_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagepost',
            old_name='image',
            new_name='post_pic',
        ),
    ]
