# Generated by Django 2.1.5 on 2019-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20191027_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagefollowinfo',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='pagefollowinfo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageinvitation',
            name='from_admin',
        ),
        migrations.RemoveField(
            model_name='pageinvitation',
            name='page',
        ),
        migrations.RemoveField(
            model_name='pageinvitation',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='PageFollowInfo',
        ),
        migrations.DeleteModel(
            name='PageInvitation',
        ),
    ]
