# Generated by Django 2.1.5 on 2019-10-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20191027_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepost',
            name='post_pic',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='page_post_pic/'),
        ),
    ]
