# Generated by Django 2.1.5 on 2019-10-23 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('group_pic', models.ImageField(blank=True, default='profile_pics/kishan.jpg', upload_to='group_pics/')),
                ('biography', models.TextField(max_length=200)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
