# Generated by Django 2.1.5 on 2019-10-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofileinfo',
            name='fee',
            field=models.IntegerField(default=0, max_length=1000),
        ),
    ]
