# Generated by Django 2.1.5 on 2019-10-23 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_auto_20191023_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofileinfo',
            name='admin',
        ),
        migrations.AddField(
            model_name='groupprofileinfo',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupprofileinfo',
            name='fee',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
