# Generated by Django 2.1.5 on 2019-10-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20191023_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupprofileinfo',
            old_name='admin_id',
            new_name='admin',
        ),
    ]
