# Generated by Django 2.1.5 on 2019-10-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_auto_20191023_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofileinfo',
            name='group_pic',
            field=models.ImageField(blank=True, default='group_profile_pics/logo.png', upload_to='group_profile_pics/'),
        ),
    ]
