# Generated by Django 2.1.5 on 2019-10-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_grouprequestinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprequestinfo',
            name='group',
        ),
    ]
