# Generated by Django 2.1.5 on 2019-10-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_grouprequestinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouprequestinfo',
            old_name='from_user_id',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='grouprequestinfo',
            old_name='to_admin_id',
            new_name='to_admin',
        ),
    ]
