# Generated by Django 2.1.5 on 2019-10-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('groups', '0014_remove_grouprequestinfo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprequestinfo',
            name='group',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
